# Generated by Django 4.2.4 on 2023-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('deviceid', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('bus_stop', models.IntegerField()),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('dwell_time', models.DurationField()),
                ('dwell_time_in_seconds_old', models.FloatField()),
                ('day_of_week', models.IntegerField()),
                ('time_of_day', models.FloatField()),
                ('Sunday_holiday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('weekday_end', models.IntegerField()),
                ('week_no', models.IntegerField()),
                ('dt_w_1', models.FloatField()),
                ('dt_w_2', models.FloatField()),
                ('dt_w_3', models.FloatField()),
                ('dt_t_1', models.FloatField()),
                ('dt_t_2', models.FloatField()),
                ('dt_n_1', models.FloatField()),
                ('dt_n_2', models.FloatField()),
                ('dt_n_3', models.FloatField()),
                ('hour_of_day', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('temp', models.FloatField()),
                ('precip', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('conditions', models.CharField(max_length=100)),
                ('rt_n_1', models.FloatField()),
                ('stop_type', models.CharField(max_length=10)),
                ('dwell_time_in_seconds', models.FloatField()),
            ],
            options={
                'db_table': 'bus_stop_times',
            },
        ),
    ]
