# Generated by Django 4.2.4 on 2023-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_busstoptimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDwellTimePredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_101', models.FloatField()),
                ('stop_102', models.FloatField()),
                ('stop_103', models.FloatField()),
                ('stop_104', models.FloatField()),
                ('stop_105', models.FloatField()),
                ('stop_106', models.FloatField()),
                ('stop_107', models.FloatField()),
                ('stop_108', models.FloatField()),
                ('stop_109', models.FloatField()),
                ('stop_110', models.FloatField()),
                ('stop_111', models.FloatField()),
                ('stop_112', models.FloatField()),
                ('stop_113', models.FloatField()),
                ('stop_114', models.FloatField()),
            ],
            options={
                'db_table': 'bus_dwell_time_predictions',
            },
        ),
        migrations.CreateModel(
            name='BusRunningPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_1', models.FloatField()),
                ('segment_2', models.FloatField()),
                ('segment_3', models.FloatField()),
                ('segment_4', models.FloatField()),
                ('segment_5', models.FloatField()),
                ('segment_6', models.FloatField()),
                ('segment_7', models.FloatField()),
                ('segment_8', models.FloatField()),
                ('segment_9', models.FloatField()),
                ('segment_10', models.FloatField()),
                ('segment_11', models.FloatField()),
                ('segment_12', models.FloatField()),
                ('segment_13', models.FloatField()),
                ('segment_14', models.FloatField()),
                ('segment_15', models.FloatField()),
            ],
            options={
                'db_table': 'bus_run_time_predictions',
            },
        ),
    ]
