# Generated by Django 4.2.4 on 2023-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_busdwelltimepredictions_busrunningpredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'date_and_time',
            },
        ),
    ]
