# Generated by Django 4.2.4 on 2023-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busArrivalTime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('101_ArrivalTime', models.CharField(max_length=255)),
                ('102_ArrivalTime', models.CharField(max_length=255)),
                ('103_ArrivalTime', models.CharField(max_length=255)),
                ('104_ArrivalTime', models.CharField(max_length=255)),
                ('105_ArrivalTime', models.CharField(max_length=255)),
                ('106_ArrivalTime', models.CharField(max_length=255)),
                ('107_ArrivalTime', models.CharField(max_length=255)),
                ('108_ArrivalTime', models.CharField(max_length=255)),
                ('109_ArrivalTime', models.CharField(max_length=255)),
                ('110_ArrivalTime', models.CharField(max_length=255)),
                ('111_ArrivalTime', models.CharField(max_length=255)),
                ('112_ArrivalTime', models.CharField(max_length=255)),
                ('113_ArrivalTime', models.CharField(max_length=255)),
                ('114_ArrivalTime', models.CharField(max_length=255)),
                ('115_ArrivalTime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'arrival_times',
            },
        ),
    ]
