# Generated by Django 4.2.4 on 2023-09-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busArrivalTime', '0002_arrivaltimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='101_ArrivalTime',
            new_name='101',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='102_ArrivalTime',
            new_name='102',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='103_ArrivalTime',
            new_name='103',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='104_ArrivalTime',
            new_name='104',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='105_ArrivalTime',
            new_name='105',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='106_ArrivalTime',
            new_name='106',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='107_ArrivalTime',
            new_name='107',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='108_ArrivalTime',
            new_name='108',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='109_ArrivalTime',
            new_name='109',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='110_ArrivalTime',
            new_name='110',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='111_ArrivalTime',
            new_name='111',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='112_ArrivalTime',
            new_name='112',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='113_ArrivalTime',
            new_name='113',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='114_ArrivalTime',
            new_name='114',
        ),
        migrations.RenameField(
            model_name='arrivaltimes',
            old_name='115_ArrivalTime',
            new_name='115',
        ),
    ]
