# Generated by Django 4.2.4 on 2023-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busArrivalTime', '0003_rename_101_arrivaltime_arrivaltimes_101_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivaltimes',
            name='latitute',
            field=models.FloatField(default=7.292462226),
        ),
        migrations.AddField(
            model_name='arrivaltimes',
            name='longitude',
            field=models.FloatField(default=80.6349778),
        ),
    ]
