# Generated by Django 4.2.4 on 2023-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busArrivalTime', '0004_arrivaltimes_latitute_arrivaltimes_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivaltimes',
            name='deviceid',
            field=models.IntegerField(default=0),
        ),
    ]
